/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdministratorRouteImport } from './routes/administrator'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdministratorIndexRouteImport } from './routes/administrator.index'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as AdministratorUsersRouteImport } from './routes/administrator.users'
import { Route as AdministratorThemeRouteImport } from './routes/administrator.theme'
import { Route as AdministratorTentangRouteImport } from './routes/administrator.tentang'
import { Route as AdministratorSectionsRouteImport } from './routes/administrator.sections'
import { Route as AdministratorPagesRouteImport } from './routes/administrator.pages'
import { Route as AdministratorMitraRouteImport } from './routes/administrator.mitra'
import { Route as AdministratorMenuRouteImport } from './routes/administrator.menu'
import { Route as AdministratorLayananRouteImport } from './routes/administrator.layanan'
import { Route as AdministratorKontakRouteImport } from './routes/administrator.kontak'
import { Route as AdministratorJamBesukRouteImport } from './routes/administrator.jam-besuk'
import { Route as AdministratorInstagramRouteImport } from './routes/administrator.instagram'
import { Route as AdministratorHeroSliderRouteImport } from './routes/administrator.hero-slider'
import { Route as AdministratorHeroSettingsRouteImport } from './routes/administrator.hero-settings'
import { Route as AdministratorHeroContentRouteImport } from './routes/administrator.hero-content'
import { Route as AdministratorFaqRouteImport } from './routes/administrator.faq'
import { Route as AdministratorDokterRouteImport } from './routes/administrator.dokter'
import { Route as AdministratorChatbotRouteImport } from './routes/administrator.chatbot'
import { Route as AdministratorBackupRouteImport } from './routes/administrator.backup'
import { Route as AdministratorAnalyticsRouteImport } from './routes/administrator.analytics'
import { Route as ApiPublicTrackRouteImport } from './routes/api/public/track'
import { Route as ApiPublicIgImageRouteImport } from './routes/api/public/ig-image'
import { Route as ApiPublicChatbotChatRouteImport } from './routes/api/public/chatbot-chat'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministratorRoute = AdministratorRouteImport.update({
  id: '/administrator',
  path: '/administrator',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministratorIndexRoute = AdministratorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdministratorRoute,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministratorUsersRoute = AdministratorUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdministratorRoute,
} as any)
const AdministratorThemeRoute = AdministratorThemeRouteImport.update({
  id: '/theme',
  path: '/theme',
  getParentRoute: () => AdministratorRoute,
} as any)
const AdministratorTentangRoute = AdministratorTentangRouteImport.update({
  id: '/tentang',
  path: '/tentang',
  getParentRoute: () => AdministratorRoute,
} as any)
const AdministratorSectionsRoute = AdministratorSectionsRouteImport.update({
  id: '/sections',
  path: '/sections',
  getParentRoute: () => AdministratorRoute,
} as any)
const AdministratorPagesRoute = AdministratorPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => AdministratorRoute,
} as any)
const AdministratorMitraRoute = AdministratorMitraRouteImport.update({
  id: '/mitra',
  path: '/mitra',
  getParentRoute: () => AdministratorRoute,
} as any)
const AdministratorMenuRoute = AdministratorMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AdministratorRoute,
} as any)
const AdministratorLayananRoute = AdministratorLayananRouteImport.update({
  id: '/layanan',
  path: '/layanan',
  getParentRoute: () => AdministratorRoute,
} as any)
const AdministratorKontakRoute = AdministratorKontakRouteImport.update({
  id: '/kontak',
  path: '/kontak',
  getParentRoute: () => AdministratorRoute,
} as any)
const AdministratorJamBesukRoute = AdministratorJamBesukRouteImport.update({
  id: '/jam-besuk',
  path: '/jam-besuk',
  getParentRoute: () => AdministratorRoute,
} as any)
const AdministratorInstagramRoute = AdministratorInstagramRouteImport.update({
  id: '/instagram',
  path: '/instagram',
  getParentRoute: () => AdministratorRoute,
} as any)
const AdministratorHeroSliderRoute = AdministratorHeroSliderRouteImport.update({
  id: '/hero-slider',
  path: '/hero-slider',
  getParentRoute: () => AdministratorRoute,
} as any)
const AdministratorHeroSettingsRoute =
  AdministratorHeroSettingsRouteImport.update({
    id: '/hero-settings',
    path: '/hero-settings',
    getParentRoute: () => AdministratorRoute,
  } as any)
const AdministratorHeroContentRoute =
  AdministratorHeroContentRouteImport.update({
    id: '/hero-content',
    path: '/hero-content',
    getParentRoute: () => AdministratorRoute,
  } as any)
const AdministratorFaqRoute = AdministratorFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => AdministratorRoute,
} as any)
const AdministratorDokterRoute = AdministratorDokterRouteImport.update({
  id: '/dokter',
  path: '/dokter',
  getParentRoute: () => AdministratorRoute,
} as any)
const AdministratorChatbotRoute = AdministratorChatbotRouteImport.update({
  id: '/chatbot',
  path: '/chatbot',
  getParentRoute: () => AdministratorRoute,
} as any)
const AdministratorBackupRoute = AdministratorBackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => AdministratorRoute,
} as any)
const AdministratorAnalyticsRoute = AdministratorAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdministratorRoute,
} as any)
const ApiPublicTrackRoute = ApiPublicTrackRouteImport.update({
  id: '/api/public/track',
  path: '/api/public/track',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIgImageRoute = ApiPublicIgImageRouteImport.update({
  id: '/api/public/ig-image',
  path: '/api/public/ig-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicChatbotChatRoute = ApiPublicChatbotChatRouteImport.update({
  id: '/api/public/chatbot-chat',
  path: '/api/public/chatbot-chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/administrator': typeof AdministratorRouteWithChildren
  '/auth': typeof AuthRoute
  '/administrator/analytics': typeof AdministratorAnalyticsRoute
  '/administrator/backup': typeof AdministratorBackupRoute
  '/administrator/chatbot': typeof AdministratorChatbotRoute
  '/administrator/dokter': typeof AdministratorDokterRoute
  '/administrator/faq': typeof AdministratorFaqRoute
  '/administrator/hero-content': typeof AdministratorHeroContentRoute
  '/administrator/hero-settings': typeof AdministratorHeroSettingsRoute
  '/administrator/hero-slider': typeof AdministratorHeroSliderRoute
  '/administrator/instagram': typeof AdministratorInstagramRoute
  '/administrator/jam-besuk': typeof AdministratorJamBesukRoute
  '/administrator/kontak': typeof AdministratorKontakRoute
  '/administrator/layanan': typeof AdministratorLayananRoute
  '/administrator/menu': typeof AdministratorMenuRoute
  '/administrator/mitra': typeof AdministratorMitraRoute
  '/administrator/pages': typeof AdministratorPagesRoute
  '/administrator/sections': typeof AdministratorSectionsRoute
  '/administrator/tentang': typeof AdministratorTentangRoute
  '/administrator/theme': typeof AdministratorThemeRoute
  '/administrator/users': typeof AdministratorUsersRoute
  '/p/$slug': typeof PSlugRoute
  '/administrator/': typeof AdministratorIndexRoute
  '/api/public/chatbot-chat': typeof ApiPublicChatbotChatRoute
  '/api/public/ig-image': typeof ApiPublicIgImageRoute
  '/api/public/track': typeof ApiPublicTrackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/administrator/analytics': typeof AdministratorAnalyticsRoute
  '/administrator/backup': typeof AdministratorBackupRoute
  '/administrator/chatbot': typeof AdministratorChatbotRoute
  '/administrator/dokter': typeof AdministratorDokterRoute
  '/administrator/faq': typeof AdministratorFaqRoute
  '/administrator/hero-content': typeof AdministratorHeroContentRoute
  '/administrator/hero-settings': typeof AdministratorHeroSettingsRoute
  '/administrator/hero-slider': typeof AdministratorHeroSliderRoute
  '/administrator/instagram': typeof AdministratorInstagramRoute
  '/administrator/jam-besuk': typeof AdministratorJamBesukRoute
  '/administrator/kontak': typeof AdministratorKontakRoute
  '/administrator/layanan': typeof AdministratorLayananRoute
  '/administrator/menu': typeof AdministratorMenuRoute
  '/administrator/mitra': typeof AdministratorMitraRoute
  '/administrator/pages': typeof AdministratorPagesRoute
  '/administrator/sections': typeof AdministratorSectionsRoute
  '/administrator/tentang': typeof AdministratorTentangRoute
  '/administrator/theme': typeof AdministratorThemeRoute
  '/administrator/users': typeof AdministratorUsersRoute
  '/p/$slug': typeof PSlugRoute
  '/administrator': typeof AdministratorIndexRoute
  '/api/public/chatbot-chat': typeof ApiPublicChatbotChatRoute
  '/api/public/ig-image': typeof ApiPublicIgImageRoute
  '/api/public/track': typeof ApiPublicTrackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/administrator': typeof AdministratorRouteWithChildren
  '/auth': typeof AuthRoute
  '/administrator/analytics': typeof AdministratorAnalyticsRoute
  '/administrator/backup': typeof AdministratorBackupRoute
  '/administrator/chatbot': typeof AdministratorChatbotRoute
  '/administrator/dokter': typeof AdministratorDokterRoute
  '/administrator/faq': typeof AdministratorFaqRoute
  '/administrator/hero-content': typeof AdministratorHeroContentRoute
  '/administrator/hero-settings': typeof AdministratorHeroSettingsRoute
  '/administrator/hero-slider': typeof AdministratorHeroSliderRoute
  '/administrator/instagram': typeof AdministratorInstagramRoute
  '/administrator/jam-besuk': typeof AdministratorJamBesukRoute
  '/administrator/kontak': typeof AdministratorKontakRoute
  '/administrator/layanan': typeof AdministratorLayananRoute
  '/administrator/menu': typeof AdministratorMenuRoute
  '/administrator/mitra': typeof AdministratorMitraRoute
  '/administrator/pages': typeof AdministratorPagesRoute
  '/administrator/sections': typeof AdministratorSectionsRoute
  '/administrator/tentang': typeof AdministratorTentangRoute
  '/administrator/theme': typeof AdministratorThemeRoute
  '/administrator/users': typeof AdministratorUsersRoute
  '/p/$slug': typeof PSlugRoute
  '/administrator/': typeof AdministratorIndexRoute
  '/api/public/chatbot-chat': typeof ApiPublicChatbotChatRoute
  '/api/public/ig-image': typeof ApiPublicIgImageRoute
  '/api/public/track': typeof ApiPublicTrackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/administrator'
    | '/auth'
    | '/administrator/analytics'
    | '/administrator/backup'
    | '/administrator/chatbot'
    | '/administrator/dokter'
    | '/administrator/faq'
    | '/administrator/hero-content'
    | '/administrator/hero-settings'
    | '/administrator/hero-slider'
    | '/administrator/instagram'
    | '/administrator/jam-besuk'
    | '/administrator/kontak'
    | '/administrator/layanan'
    | '/administrator/menu'
    | '/administrator/mitra'
    | '/administrator/pages'
    | '/administrator/sections'
    | '/administrator/tentang'
    | '/administrator/theme'
    | '/administrator/users'
    | '/p/$slug'
    | '/administrator/'
    | '/api/public/chatbot-chat'
    | '/api/public/ig-image'
    | '/api/public/track'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/administrator/analytics'
    | '/administrator/backup'
    | '/administrator/chatbot'
    | '/administrator/dokter'
    | '/administrator/faq'
    | '/administrator/hero-content'
    | '/administrator/hero-settings'
    | '/administrator/hero-slider'
    | '/administrator/instagram'
    | '/administrator/jam-besuk'
    | '/administrator/kontak'
    | '/administrator/layanan'
    | '/administrator/menu'
    | '/administrator/mitra'
    | '/administrator/pages'
    | '/administrator/sections'
    | '/administrator/tentang'
    | '/administrator/theme'
    | '/administrator/users'
    | '/p/$slug'
    | '/administrator'
    | '/api/public/chatbot-chat'
    | '/api/public/ig-image'
    | '/api/public/track'
  id:
    | '__root__'
    | '/'
    | '/administrator'
    | '/auth'
    | '/administrator/analytics'
    | '/administrator/backup'
    | '/administrator/chatbot'
    | '/administrator/dokter'
    | '/administrator/faq'
    | '/administrator/hero-content'
    | '/administrator/hero-settings'
    | '/administrator/hero-slider'
    | '/administrator/instagram'
    | '/administrator/jam-besuk'
    | '/administrator/kontak'
    | '/administrator/layanan'
    | '/administrator/menu'
    | '/administrator/mitra'
    | '/administrator/pages'
    | '/administrator/sections'
    | '/administrator/tentang'
    | '/administrator/theme'
    | '/administrator/users'
    | '/p/$slug'
    | '/administrator/'
    | '/api/public/chatbot-chat'
    | '/api/public/ig-image'
    | '/api/public/track'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdministratorRoute: typeof AdministratorRouteWithChildren
  AuthRoute: typeof AuthRoute
  PSlugRoute: typeof PSlugRoute
  ApiPublicChatbotChatRoute: typeof ApiPublicChatbotChatRoute
  ApiPublicIgImageRoute: typeof ApiPublicIgImageRoute
  ApiPublicTrackRoute: typeof ApiPublicTrackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administrator': {
      id: '/administrator'
      path: '/administrator'
      fullPath: '/administrator'
      preLoaderRoute: typeof AdministratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administrator/': {
      id: '/administrator/'
      path: '/'
      fullPath: '/administrator/'
      preLoaderRoute: typeof AdministratorIndexRouteImport
      parentRoute: typeof AdministratorRoute
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administrator/users': {
      id: '/administrator/users'
      path: '/users'
      fullPath: '/administrator/users'
      preLoaderRoute: typeof AdministratorUsersRouteImport
      parentRoute: typeof AdministratorRoute
    }
    '/administrator/theme': {
      id: '/administrator/theme'
      path: '/theme'
      fullPath: '/administrator/theme'
      preLoaderRoute: typeof AdministratorThemeRouteImport
      parentRoute: typeof AdministratorRoute
    }
    '/administrator/tentang': {
      id: '/administrator/tentang'
      path: '/tentang'
      fullPath: '/administrator/tentang'
      preLoaderRoute: typeof AdministratorTentangRouteImport
      parentRoute: typeof AdministratorRoute
    }
    '/administrator/sections': {
      id: '/administrator/sections'
      path: '/sections'
      fullPath: '/administrator/sections'
      preLoaderRoute: typeof AdministratorSectionsRouteImport
      parentRoute: typeof AdministratorRoute
    }
    '/administrator/pages': {
      id: '/administrator/pages'
      path: '/pages'
      fullPath: '/administrator/pages'
      preLoaderRoute: typeof AdministratorPagesRouteImport
      parentRoute: typeof AdministratorRoute
    }
    '/administrator/mitra': {
      id: '/administrator/mitra'
      path: '/mitra'
      fullPath: '/administrator/mitra'
      preLoaderRoute: typeof AdministratorMitraRouteImport
      parentRoute: typeof AdministratorRoute
    }
    '/administrator/menu': {
      id: '/administrator/menu'
      path: '/menu'
      fullPath: '/administrator/menu'
      preLoaderRoute: typeof AdministratorMenuRouteImport
      parentRoute: typeof AdministratorRoute
    }
    '/administrator/layanan': {
      id: '/administrator/layanan'
      path: '/layanan'
      fullPath: '/administrator/layanan'
      preLoaderRoute: typeof AdministratorLayananRouteImport
      parentRoute: typeof AdministratorRoute
    }
    '/administrator/kontak': {
      id: '/administrator/kontak'
      path: '/kontak'
      fullPath: '/administrator/kontak'
      preLoaderRoute: typeof AdministratorKontakRouteImport
      parentRoute: typeof AdministratorRoute
    }
    '/administrator/jam-besuk': {
      id: '/administrator/jam-besuk'
      path: '/jam-besuk'
      fullPath: '/administrator/jam-besuk'
      preLoaderRoute: typeof AdministratorJamBesukRouteImport
      parentRoute: typeof AdministratorRoute
    }
    '/administrator/instagram': {
      id: '/administrator/instagram'
      path: '/instagram'
      fullPath: '/administrator/instagram'
      preLoaderRoute: typeof AdministratorInstagramRouteImport
      parentRoute: typeof AdministratorRoute
    }
    '/administrator/hero-slider': {
      id: '/administrator/hero-slider'
      path: '/hero-slider'
      fullPath: '/administrator/hero-slider'
      preLoaderRoute: typeof AdministratorHeroSliderRouteImport
      parentRoute: typeof AdministratorRoute
    }
    '/administrator/hero-settings': {
      id: '/administrator/hero-settings'
      path: '/hero-settings'
      fullPath: '/administrator/hero-settings'
      preLoaderRoute: typeof AdministratorHeroSettingsRouteImport
      parentRoute: typeof AdministratorRoute
    }
    '/administrator/hero-content': {
      id: '/administrator/hero-content'
      path: '/hero-content'
      fullPath: '/administrator/hero-content'
      preLoaderRoute: typeof AdministratorHeroContentRouteImport
      parentRoute: typeof AdministratorRoute
    }
    '/administrator/faq': {
      id: '/administrator/faq'
      path: '/faq'
      fullPath: '/administrator/faq'
      preLoaderRoute: typeof AdministratorFaqRouteImport
      parentRoute: typeof AdministratorRoute
    }
    '/administrator/dokter': {
      id: '/administrator/dokter'
      path: '/dokter'
      fullPath: '/administrator/dokter'
      preLoaderRoute: typeof AdministratorDokterRouteImport
      parentRoute: typeof AdministratorRoute
    }
    '/administrator/chatbot': {
      id: '/administrator/chatbot'
      path: '/chatbot'
      fullPath: '/administrator/chatbot'
      preLoaderRoute: typeof AdministratorChatbotRouteImport
      parentRoute: typeof AdministratorRoute
    }
    '/administrator/backup': {
      id: '/administrator/backup'
      path: '/backup'
      fullPath: '/administrator/backup'
      preLoaderRoute: typeof AdministratorBackupRouteImport
      parentRoute: typeof AdministratorRoute
    }
    '/administrator/analytics': {
      id: '/administrator/analytics'
      path: '/analytics'
      fullPath: '/administrator/analytics'
      preLoaderRoute: typeof AdministratorAnalyticsRouteImport
      parentRoute: typeof AdministratorRoute
    }
    '/api/public/track': {
      id: '/api/public/track'
      path: '/api/public/track'
      fullPath: '/api/public/track'
      preLoaderRoute: typeof ApiPublicTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ig-image': {
      id: '/api/public/ig-image'
      path: '/api/public/ig-image'
      fullPath: '/api/public/ig-image'
      preLoaderRoute: typeof ApiPublicIgImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/chatbot-chat': {
      id: '/api/public/chatbot-chat'
      path: '/api/public/chatbot-chat'
      fullPath: '/api/public/chatbot-chat'
      preLoaderRoute: typeof ApiPublicChatbotChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdministratorRouteChildren {
  AdministratorAnalyticsRoute: typeof AdministratorAnalyticsRoute
  AdministratorBackupRoute: typeof AdministratorBackupRoute
  AdministratorChatbotRoute: typeof AdministratorChatbotRoute
  AdministratorDokterRoute: typeof AdministratorDokterRoute
  AdministratorFaqRoute: typeof AdministratorFaqRoute
  AdministratorHeroContentRoute: typeof AdministratorHeroContentRoute
  AdministratorHeroSettingsRoute: typeof AdministratorHeroSettingsRoute
  AdministratorHeroSliderRoute: typeof AdministratorHeroSliderRoute
  AdministratorInstagramRoute: typeof AdministratorInstagramRoute
  AdministratorJamBesukRoute: typeof AdministratorJamBesukRoute
  AdministratorKontakRoute: typeof AdministratorKontakRoute
  AdministratorLayananRoute: typeof AdministratorLayananRoute
  AdministratorMenuRoute: typeof AdministratorMenuRoute
  AdministratorMitraRoute: typeof AdministratorMitraRoute
  AdministratorPagesRoute: typeof AdministratorPagesRoute
  AdministratorSectionsRoute: typeof AdministratorSectionsRoute
  AdministratorTentangRoute: typeof AdministratorTentangRoute
  AdministratorThemeRoute: typeof AdministratorThemeRoute
  AdministratorUsersRoute: typeof AdministratorUsersRoute
  AdministratorIndexRoute: typeof AdministratorIndexRoute
}

const AdministratorRouteChildren: AdministratorRouteChildren = {
  AdministratorAnalyticsRoute: AdministratorAnalyticsRoute,
  AdministratorBackupRoute: AdministratorBackupRoute,
  AdministratorChatbotRoute: AdministratorChatbotRoute,
  AdministratorDokterRoute: AdministratorDokterRoute,
  AdministratorFaqRoute: AdministratorFaqRoute,
  AdministratorHeroContentRoute: AdministratorHeroContentRoute,
  AdministratorHeroSettingsRoute: AdministratorHeroSettingsRoute,
  AdministratorHeroSliderRoute: AdministratorHeroSliderRoute,
  AdministratorInstagramRoute: AdministratorInstagramRoute,
  AdministratorJamBesukRoute: AdministratorJamBesukRoute,
  AdministratorKontakRoute: AdministratorKontakRoute,
  AdministratorLayananRoute: AdministratorLayananRoute,
  AdministratorMenuRoute: AdministratorMenuRoute,
  AdministratorMitraRoute: AdministratorMitraRoute,
  AdministratorPagesRoute: AdministratorPagesRoute,
  AdministratorSectionsRoute: AdministratorSectionsRoute,
  AdministratorTentangRoute: AdministratorTentangRoute,
  AdministratorThemeRoute: AdministratorThemeRoute,
  AdministratorUsersRoute: AdministratorUsersRoute,
  AdministratorIndexRoute: AdministratorIndexRoute,
}

const AdministratorRouteWithChildren = AdministratorRoute._addFileChildren(
  AdministratorRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdministratorRoute: AdministratorRouteWithChildren,
  AuthRoute: AuthRoute,
  PSlugRoute: PSlugRoute,
  ApiPublicChatbotChatRoute: ApiPublicChatbotChatRoute,
  ApiPublicIgImageRoute: ApiPublicIgImageRoute,
  ApiPublicTrackRoute: ApiPublicTrackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
