
ALTER TABLE public.hero_content
  ADD COLUMN IF NOT EXISTS smart_word TEXT NOT NULL DEFAULT 'SMART',
  ADD COLUMN IF NOT EXISTS smart_desc TEXT NOT NULL DEFAULT '— Sehat · Mutu · Amanah · Ramah · Terampil',
  ADD COLUMN IF NOT EXISTS smart_color TEXT NOT NULL DEFAULT '#D4AF37',
  ADD COLUMN IF NOT EXISTS smart_desc_color TEXT NOT NULL DEFAULT '#FFFFFF',
  ADD COLUMN IF NOT EXISTS smart_font_family TEXT NOT NULL DEFAULT 'sans',
  ADD COLUMN IF NOT EXISTS smart_font_size INTEGER NOT NULL DEFAULT 20,
  ADD COLUMN IF NOT EXISTS pendaftaran_wa_number TEXT NOT NULL DEFAULT '6289646710859',
  ADD COLUMN IF NOT EXISTS pendaftaran_wa_prolog TEXT NOT NULL DEFAULT 'Hi RSU AISYIYAH Purworejo, saya ingin mendaftar.';
